version: '2'
services:
  dev:
    image: keboola/processor-add-row-number-column
    tty: true
    stdin_open: true
    volumes:
      - .:/code

  processor-add-row-number-column:
    build: .
    image: keboola/processor-add-row-number-column
    tty: true
    stdin_open: true

  tests:
    image: keboola/processor-add-row-number-column
    tty: true
    stdin_open: true
    volumes:
      - .:/code
    command: php /code/tests/run.php
